### ISSUE TITLE
Dependency "CSV.swift" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by pratik-kate** [yaslab/CSV.swift#131]
I am trying to install CSV.swift dependency using carthage, but facing this issue,

```
Dependency "CSV.swift" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/yaslab/CSV.swift/issues/new
I have tried re-installing carthage and the dependency but it is still not working.
```

Also tried with this command,
`Carthage update --platform iOS`
Any solution to this problem, also if I am missing something please let me know.

**Comment by yaslab** [comment]
This library no longer supports Carthage since version 2.5.0. (This repository no longer contains `*.xcodeproj`)

To build XCFramework with Carthage, you need to use version 2.4.3 of this library.

Alternatively, you should be able to build XCFramework using [Scipio](https://github.com/giginet/Scipio), a tool that supports SwiftPM. (I've never used it...)

**Comment by pratik-kate** [comment]
Thank you @yaslab for the clarification. It solved my issue.
